"""add comment

Revision ID: 52fde02defff
Revises: c115657903e9
Create Date: 2024-12-05 03:34:14.949300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fde02defff'
down_revision: Union[str, None] = 'c115657903e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_image', sa.String(), nullable=False),
    sa.Column('twit_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['twit_id'], ['twit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
