"""remove count_like

Revision ID: 6616beb730cb
Revises: 0c61654f5aef
Create Date: 2024-12-01 05:05:40.485553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6616beb730cb'
down_revision: Union[str, None] = '0c61654f5aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twit', 'count_like')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twit', sa.Column('count_like', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
