version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - demo
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - demo
  nginx:
    image: nginx:latest
    ports:
      - "80:80"

    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - demo
    depends_on:
      - app



networks:
  demo:
    external: true